//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Zapato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Zapato()
        {
            this.tb_Foto = new HashSet<tb_Foto>();
        }
    
        public int Id { get; set; }
        public string Color { get; set; }
        public string Modelo { get; set; }
        public int Precio { get; set; }
        public Nullable<int> Descuento { get; set; }
        public int Talla { get; set; }
        public bool Estado { get; set; }
        public string Genero { get; set; }
        public int Id_Proveedor { get; set; }
        public int Id_Marca { get; set; }
        public int Id_Categoria { get; set; }
    
        public virtual tb_Categoria tb_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Foto> tb_Foto { get; set; }
        public virtual tb_Marca tb_Marca { get; set; }
        public virtual tb_Proveedor tb_Proveedor { get; set; }
    }
}
