//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EllaYelDBEntities : DbContext
    {
        public EllaYelDBEntities()
            : base("name=EllaYelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Categoria> tb_Categoria { get; set; }
        public virtual DbSet<tb_Cliente> tb_Cliente { get; set; }
        public virtual DbSet<tb_Foto> tb_Foto { get; set; }
        public virtual DbSet<tb_Marca> tb_Marca { get; set; }
        public virtual DbSet<tb_Proveedor> tb_Proveedor { get; set; }
        public virtual DbSet<tb_Usuario_Vendedor> tb_Usuario_Vendedor { get; set; }
        public virtual DbSet<tb_Vendedor> tb_Vendedor { get; set; }
        public virtual DbSet<tb_Zapato> tb_Zapato { get; set; }
    }
}
